import { NgModule } from '@angular/core';
import { MatButtonModule,
        MatIconModule,
        MatToolbarModule,
        MatSidenavModule,
        MatDividerModule,
        MatMenuModule,
        MatDialogModule,
        MatTabsModule,
        MatTooltipModule,
        MatCardModule,
        MatChipsModule,
        MatAutocompleteModule,
        MatFormFieldModule, 
        MatInputModule,
        MatSelectModule,
        MatListModule,
        MatCheckboxModule } from '@angular/material';

@NgModule({
    imports:[MatButtonModule,
            MatIconModule,
            MatToolbarModule,
            MatSidenavModule,
            MatDividerModule,
            MatMenuModule,
            MatDialogModule,
            MatTabsModule,
            MatTooltipModule,
            MatCardModule,
            MatChipsModule,
            MatAutocompleteModule,
            MatFormFieldModule,
            MatInputModule,
            MatSelectModule,
            MatListModule,
            MatCheckboxModule ],
    exports:[MatButtonModule,
            MatIconModule,
            MatToolbarModule,
            MatSidenavModule,
            MatDividerModule,
            MatMenuModule,
            MatDialogModule,
            MatTabsModule,
            MatTooltipModule,
            MatCardModule,
            MatChipsModule,
            MatAutocompleteModule,
            MatFormFieldModule,
            MatInputModule,
            MatSelectModule,
            MatListModule,
            MatCheckboxModule ]
})
export class MaterialModule {}